version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "lambda"
s3_bucket = "sam-artifacts-oppfy"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
confirm_changeset = true
resolve_s3 = true
s3_prefix = "lambda"
disable_rollback = true
image_repositories = []
[default.build.parameters]
beta_features = true
[default.sync.parameters]
beta_features = true
